// <auto-generated />
namespace WPF_Sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addedmm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmm));
        
        string IMigrationMetadata.Id
        {
            get { return "201807241825506_added-m-m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
